# Plan for today:
- PyTorch installation
- PyTorch basics
- Data loading and simple models in PyTorch (linear regression, images of digits)

# Install pytorch and torchvision
Installation instruction: https://pytorch.org/  

Different commands for GPU version -> all in PyTorch website

# PyTorch resources
- https://pytorch.org/tutorials/
- https://github.com/yunjey/pytorch-tutorial
- http://cs231n.stanford.edu/

# PyTorch basics

## Tensors



In [100]:
import torch

Basic datatype in PyTorch is a Tensor (syntax very similar to numpy array). https://pytorch.org/docs/stable/tensors.html  
**A `torch.Tensor` is a multi-dimensional matrix containing elements of a single data type.**

- A 0D tensor is scalar
- A 1D tensor is a vector 
- A 2D tensor is a matrix 
- A 3D tensor can be seen as a vector of identically size matrix
- A 4D tensor can be seen as a matrix of identically size matrices


In [101]:
data = torch.tensor([1, 2, 3])
print(data)
print(data.size())
print(data.dtype)

tensor([1, 2, 3])
torch.Size([3])
torch.int64


In [102]:
data = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(data)
print(data.size())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [103]:
#this creates a tensor matrix
a =torch.zeros((3, 4))
torch.zeros_like(data) #instead of the numbers u give it a tensor and it will return a tensor just as the given tensor but full of zeros
#a =a.cuda()
a.device

device(type='cpu')

In [104]:
b=torch.ones((3, 4))
b.device

device(type='cpu')

In [105]:
#if we do a+ b and a is on cuda and b on cpu, it wont work, they need to share the same memory, which they dont if they're on diff. devices

In [106]:
# Random numbers: uniform [0, 1)
torch.rand(3, 5)

a=2
b=6
torch.rand(3, 5) #generates numbers between 2 and 6
d=torch.rand(3,5,7) * (b-a) +a 

In [107]:
d.shape
#d.t() #doesnt work bcz the dimension should be less than 3, but u can use permute
d.permute(1,2,0) #give the order of the dim u want to permute

tensor([[[4.2830, 3.7932, 2.8655],
         [5.5491, 3.2740, 4.5635],
         [5.8491, 2.6607, 5.2881],
         [4.5197, 4.1107, 3.0496],
         [4.7145, 5.8888, 5.1027],
         [3.2659, 4.9707, 3.2981],
         [2.9477, 2.2856, 3.4455]],

        [[3.2020, 4.1189, 3.4785],
         [5.5258, 3.8720, 3.7764],
         [4.7089, 2.6490, 5.6125],
         [5.1352, 2.3615, 3.9709],
         [4.5799, 5.6508, 2.9984],
         [5.9084, 2.6815, 2.6358],
         [3.0664, 5.4831, 3.3704]],

        [[4.2960, 2.4868, 2.4667],
         [3.8618, 2.8039, 2.1928],
         [3.8917, 5.8917, 5.3720],
         [5.7658, 5.4302, 4.8104],
         [5.5847, 3.3946, 3.2381],
         [2.7781, 3.4656, 4.2828],
         [2.8392, 4.9371, 3.5047]],

        [[4.0452, 3.3015, 5.1048],
         [5.8073, 3.6290, 4.6977],
         [4.3355, 2.2353, 4.5040],
         [3.3251, 3.5567, 3.7308],
         [5.3559, 5.2490, 5.5190],
         [5.4658, 5.0260, 5.4385],
         [5.6421, 2.1725, 2.8075]],

        [[5.

In [108]:
torch.randn(2,3)

tensor([[ 0.2620,  0.1268,  0.1482],
        [-0.3788,  1.8683, -0.8748]])

In [109]:
# More Operations
x = torch.tensor([[1,2,3], [2,4,6]])
# transpose
print(x.t()) #transpose
# flatten
print(x.flatten())
# cropping
print(x[:, 1:3])

tensor([[1, 2],
        [2, 4],
        [3, 6]])
tensor([1, 2, 3, 2, 4, 6])
tensor([[2, 3],
        [4, 6]])


### For more operation see: https://pytorch.org/docs/stable/torch.html

## CPU vs GPU (CUDA)
Tensors can live on CPU or on GPU if torch is installed with Nvidia CUDA support. *CUDA tensors allow for much faster computation!*

In [110]:
torch.cuda.is_available()

False

To make code compatible with both GPU and CPU, you can set the device at the beginning of your code and always transfer your tensors/models to this device

In [111]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu') #specify use the 1st gpu

In [112]:
print(device)

cpu


In [113]:
a = torch.tensor(5, device=device)
print(a)
a.device

tensor(5)


device(type='cpu')

In [114]:
a = a.to(device)
print(a)

tensor(5)


In [115]:
a = a.to(torch.device('cpu'))
print(a)
print(a.device)

tensor(5)
cpu


## Computation

In [116]:
a = torch.tensor(5.0, requires_grad=True)  #with requires_grad, now c has a grad, meaning that c knows how a is calculated. It has a calculation func
b = torch.tensor(2.0)
print(a, b)

tensor(5., requires_grad=True) tensor(2.)


In [117]:
c = a + b
print(c)

tensor(7., grad_fn=<AddBackward0>)


In [118]:
print(c.grad) #gradient of c is none
print(c)

None
tensor(7., grad_fn=<AddBackward0>)


C:\Users\anabo\AppData\Local\Temp\ipykernel_10524\2985855999.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:497.)
  print(c.grad) #gradient of c is none


In [119]:
c = a - b
print(c)

tensor(3., grad_fn=<SubBackward0>)


In [120]:
c = a * b
print(c)

tensor(10., grad_fn=<MulBackward0>)


In [121]:
c = a / b
print(c) #c is not simply a scalar

tensor(2.5000, grad_fn=<DivBackward0>)


In [122]:
# Matrix computations
a = torch.rand(3, 4)
b = torch.rand(4, 1)
print(a)
print(b)

tensor([[0.8563, 0.4294, 0.2966, 0.9702],
        [0.5704, 0.1697, 0.0932, 0.2022],
        [0.3832, 0.6121, 0.9858, 0.7295]])
tensor([[0.0873],
        [0.4935],
        [0.3517],
        [0.5635]])


In [123]:
c = a.matmul(b)
print(c)

tensor([[0.9377],
        [0.2803],
        [1.0933]])


In [124]:
c = a @ b
print(c)

tensor([[0.9377],
        [0.2803],
        [1.0933]])


In [125]:
print(c + torch.rand(3, 1))

tensor([[0.9847],
        [1.2385],
        [1.8984]])


# PyTorch computational graph
Important property of PyTorch tensor operations - they create a **dynamic computational graph**.  
The tensor **c** knows that how it was created from **a** and **b**.  
Thanks to this, derivatives (gradients) can be computed for tensors.  
Example:  
<img src="tree-eval.png" alt="Drawing" style="width: 600px;"/>  
*Source: http://colah.github.io/posts/2015-08-Backprop/ - good blog post to understand backpropagation*

### Compute for a=2, b=1

In [126]:
# Create a and b
# Compute c, d, e
a = torch.tensor(2.0, requires_grad=True) # requires_grad is true so u can see the grad function of the calculations 
b = torch.tensor(1.0, requires_grad=True)
c = a + b
d = b + 1
e = c * d
print(a, b, c, d, e)
#this is the tree from above

tensor(2., requires_grad=True) tensor(1., requires_grad=True) tensor(3., grad_fn=<AddBackward0>) tensor(2., grad_fn=<AddBackward0>) tensor(6., grad_fn=<MulBackward0>)


In [127]:
# grad_fn stores information about computation
print(c.grad_fn)
print(e.grad_fn)

### Now we can computer derivative of $e$ w.r.t. $a, b, c, d$
<img src="tree-eval-derivs.png" alt="Drawing" style="width: 600px;"/>  

\begin{equation} 
e = c * d
\end{equation}
\begin{equation} 
\frac {\partial e} {\partial c} = d = 2
\end{equation}
\begin{equation} 
\frac {\partial e} {\partial d} = c = 3
\end{equation}
\begin{equation} 
\frac {\partial e} {\partial a} = \frac {\partial e} {\partial c} \frac {\partial c} {\partial a} = 2
\end{equation}
\begin{equation} 
\frac {\partial e} {\partial b} = \frac {\partial e} {\partial c} \frac {\partial c} {\partial b} + \frac {\partial e} {\partial d} \frac {\partial d} {\partial b} = 2 * 1 + 3 * 1 = 5
\end{equation}

Compute gradients with `torch.autograd.grad` https://pytorch.org/docs/stable/autograd.html

In [128]:
# Compute gradients with torch.autograd.grad https://pytorch.org/docs/stable/autograd.html

In [129]:
grad_a, grad_b, grad_c, grad_d = torch.autograd.grad(e, [a, b, c, d]) # get the gradient of e with respect to abcd

In [130]:
print(grad_a, grad_b, grad_c, grad_d)

tensor(2.) tensor(5.) tensor(2.) tensor(3.)


In [131]:
# Another way for leaf tensors with `backward` method

In [132]:
# Create a and b
# Compute c, d, e
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)
c = a + b
d = b + 1
e = c * d
print(a, b, c, d, e)

tensor(2., requires_grad=True) tensor(1., requires_grad=True) tensor(3., grad_fn=<AddBackward0>) tensor(2., grad_fn=<AddBackward0>) tensor(6., grad_fn=<MulBackward0>)


In [ ]:
e.backward() #lets say e is our loss (which is the final node of our computation) and we want to know its gradient, we can just do e.backward instead of torch.autograd.grad(..) and it will automatically compute all the gradients of all the weights of the nodes that serve in the calc of this e

In [ ]:
print(a.grad, b.grad, c.grad, d.grad) #but it doesnt show you it intermediate nodes, we only see the leaf nodes. We only need the gradients for our weights, which are the leaf nodes so it is fine.

tensor(2.) tensor(5.) None None


C:\Users\anabo\AppData\Local\Temp\ipykernel_10524\347313883.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:497.)
  print(a.grad, b.grad, c.grad, d.grad)
